[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lansuSql"
version = "0.1.2"
description = "Uma biblioteca robusta de repositórios genéricos combinando SQLAlchemy e Pydantic."
authors = [
    { name = "Tiago Sversut" } 
]
requires-python = ">=3.10"
dependencies = [
    "sqlalchemy>=2.0.0",
    "pydantic>=2.0.0"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0"
]

[tool.pytest.ini_options]
pythonpath = [
    "src"
]
testpaths = [
    "tests"
]